# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CBACampProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'MenuSlider', '~> 0.1.5'
pod "SimpleAnimation"
pod 'Firebase/Core'
pod 'Firebase/Storage'
pod 'Firebase/Database'
pod 'Firebase/Messaging'
pod 'Kingfisher', '~> 4.0'
pod 'GoogleSignIn'
pod 'Firebase/Auth'
pod "TextFieldEffects"
  # Pods for CBACampProject
pod 'Alamofire', '~> 5.0.0-beta.5'

  target 'CBACampProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CBACampProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
