# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CBACampProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'MenuSlider', '~> 0.1.5'
pod "SimpleAnimation"
pod 'Firebase/Analytics'
pod 'Firebase/Core'
pod 'Firebase/Storage'
pod 'Firebase/Database'
pod 'Firebase/Messaging'
pod 'Kingfisher', '~> 5.0'
pod 'ImageSlideshow', '~> 1.6'
pod 'ImageSlideshow/Kingfisher'
pod 'GoogleSignIn'
pod 'Firebase/Auth'
pod "TextFieldEffects"
pod 'Alamofire', '~> 5.0'
pod 'SwiftyJSON'
pod 'SnapKit', '~> 5.0.0'
pod 'RealmSwift'
pod "YoutubePlayer-in-WKWebView", "~> 0.2.0"
pod 'MBRadioCheckboxButton'
  # Pods for CBACampProject

  target 'CBACampProjectTests' do
    inherit! :search_paths

    pod 'SnapKit', '~> 5.0.0'
    # Pods for testing
  end

  target 'CBACampProjectUITests' do

    pod 'SnapKit', '~> 5.0.0'
    inherit! :search_paths
    # Pods for testing
  end

end
